### ISSUE TITLE
win10企业版-1709 英文版系统上效果差

### ISSUE THREAD

**Issue by lzh77** [ysc3839/TGFont#12]
目前不知道是不是英文版系统来就是这样，我是用的默认设置(雅黑)，效果如图
![qq 20180311111858](https://user-images.githubusercontent.com/16144682/37249202-09ff5290-251e-11e8-87b7-360105cc97b2.png)

**Comment by ysc3839** [comment]
不同语言的系统使用的默认字体不一样，你需要开启 debug，找到对应的字体名称。
