### ISSUE TITLE
please describe new parameter "quality" in json

### ISSUE THREAD

**Issue by f242** [ysc3839/TGFont#15]

**Comment by ysc3839** [comment]
See https://msdn.microsoft.com/en-us/library/dd145037 .

**Comment by f242** [comment]
@ysc3839 
i set "quality": NONANTIALIASED_QUALITY,
and see error
![image](https://user-images.githubusercontent.com/10371194/41429658-64ba4300-7016-11e8-8517-2bccb02dd338.png)

if i add ""
"quality": "NONANTIALIASED_QUALITY",
nothing changes

**Comment by ysc3839** [comment]
@f242 This is a integer value, not string. For example, NONANTIALIASED_QUALITY = 3, so in json is "quality": 3,.
