### ISSUE TITLE
建议支持按文件路径确定字体

### ISSUE THREAD

**Issue by Crystal-RainSlide** [ysc3839/TGFont#16]
以便选用被用于替换原字体的字体。
Windows 会将一些带有特定属性的字体，作为普通状态字体的带属性版本，而非单独的字体。Tgfont 选用字体时又只可设置 bold，或设置 Windows 定义的不够精确的字重（如不支持 450 等 CSS 支持的字重）。
使用确定路径的字体文件可有效避免此问题。

**Comment by ysc3839** [comment]
Windows GDI 本身不支持按文件路径确定字体，所以无法实现。
