### ISSUE TITLE
TG便携版，Win7 x64下没有任何效果

### ISSUE THREAD

**Issue by minmemory** [ysc3839/TGFont#17]
打开调试模式之后第一句是，[LoadUserFonts] FindFirstFile failed! (3)
但是tg目录下创建了Fonts文件夹而且把已经安装的字体又复制了一遍
没有任何效果，我的配置文件是

{   
    "fonts": {   
        "SimSun": {   
            "replace": "Noto Sans CJK SC",   
            "#size": 0,   
            "#width": 0,   
            "#weight": 0,   
            "#italic": false,    
            "#underLine": false,
            "#strikeOut": false
        },
        "Open Sans": {
            "replace": "Noto Sans CJK SC",
            "#size": 0,
            "#width": 0,
            "#weight": 0,
            "#italic": false,
            "#underLine": false,
            "#strikeOut": false
        },
        "Open Sans Semibold": {
            "replace": "Noto Sans CJK SC",
            "#size": 0,
            "#width": 0,
            "#weight": 0,
            "#italic": false,
            "#underLine": false,
            "#strikeOut": false
        },
        "Arial": {
            "replace": "Noto Sans CJK SC",
            "#size": 0,
            "#width": 0,
            "#weight": 0,
            "#italic": false,
            "#underLine": false,
            "#strikeOut": false
        },
        "MS UI Gothic": {
            "replace": "Noto Sans CJK SC",
            "#size": 0,
            "#width": 0,
            "#weight": 0,
            "#italic": false,
            "#underLine": false,
            "#strikeOut": false
        }
    },
    "debug": true
}

**Comment by ysc3839** [comment]
@minmemory 把 "Fonts" 文件夹 改名为 "fonts" 试试？

**Comment by minmemory** [comment]
本来就是小写，然后log非常长，单独占据一层

**Comment by ysc3839** [comment]
@minmemory 把 log 文件发上来看看

**Comment by minmemory** [comment]
唔，log已经长到突破github的底线了，只能丢gist~[https://gist.github.com/minmemory/98cec612fc842a73eab9aac1077ada5e](url)
另外是否可以不用fonts文件夹而直接调用系统中安装的此字体，NVMe不大希望省点空间

**Comment by ysc3839** [comment]
@minmemory Github issue 可以直接发文件。

**Comment by minmemory** [comment]
发现几行报错
[LoadUserFonts] filename = "Hiragino-Sans-GB.ttf", ret = 2, lasterror = 183
[LoadUserFonts] filename = "NotoSansCJKsc-Black.otf", ret = 2, lasterror = 183
[LoadUserFonts] filename = "NotoSansCJKsc-Bold.otf", ret = 2, lasterror = 183
[LoadUserFonts] filename = "NotoSansCJKsc-Light.otf", ret = 2, lasterror = 183
[LoadUserFonts] filename = "NotoSansCJKsc-Medium.otf", ret = 2, lasterror = 183
[LoadUserFonts] filename = "NotoSansCJKsc-Regular.otf", ret = 2, lasterror = 183
[LoadUserFonts] filename = "NotoSansCJKsc-Thin.otf", ret = 2, lasterror = 183

**Comment by ysc3839** [comment]
本来就可以直接使用系统中已经安装的字体。
README 里面写的是 `用户字体: 把字体文件放在 fonts 文件夹内, 可以直接使用, 无需安装到系统中.`

**Comment by minmemory** [comment]
这几个字体文件是我从系统中复制到D:\Telegram\fonts的

**Comment by ysc3839** [comment]
你发的这几行也没有出错。
你应该检查一下字体名称是否正确。打开字体文件，然后看看字体名称写的是什么。

**Comment by minmemory** [comment]
![tgfonts](https://user-images.githubusercontent.com/2556055/42245025-de9cc4c6-7f49-11e8-8843-4fd1189e7ce9.PNG)
目前字体的显示仍然处于一种较为鬼畜的状态

**Comment by minmemory** [comment]
我设定字体名称是用的平常做CSS用的类，在CSS上显示正常，系统中的名称是这个
![regular](https://user-images.githubusercontent.com/2556055/42245126-30c0da62-7f4a-11e8-8222-fa63bc209ffa.PNG)

**Comment by ysc3839** [comment]
那你应该使用你截图中看到的字体名称。

**Comment by minmemory** [comment]
PingFang SC正常，但是不是太适合，即便是Medium还是太细
