### ISSUE TITLE
[LoadUserFonts] FindFirstFile failed! (3)

### ISSUE THREAD

**Issue by Takwah** [ysc3839/TGFont#20]
[LoadUserFonts] FindFirstFile failed! (3)

**Comment by ysc3839** [comment]
如果使用时没有问题，那忽略即可。

**Comment by Takwah** [comment]
你好,问题是有的,就是没有任何字体变化,版本是1.3.14,使用了mactype
![image](https://user-images.githubusercontent.com/24718328/44896344-8405bb80-ad2a-11e8-8977-84868cdf8c2c.png)

**Comment by ysc3839** [comment]
@Takwah 可能和 MacType 不兼容。可以试试停用 MacType。
