### ISSUE TITLE
#size?

### ISSUE THREAD

**Issue by bestpika** [ysc3839/TGFont#22]
您好，請問 `#size` 的 flag 是不是沒作用？
因為下面這段找不到相關的 `#define`

https://github.com/ysc3839/TGFont/blob/6b255968646687521c972f019c6c42dd80ef22e3/TGFont.cpp#L33-L46

**Comment by ysc3839** [comment]
https://github.com/ysc3839/TGFont/blob/6b255968646687521c972f019c6c42dd80ef22e3/TGFont.cpp#L205
请看这里。
