### ISSUE TITLE
telegram desktop 1.4.8 beta上，部分字体没有替换成功

### ISSUE THREAD

**Issue by CeresCa** [ysc3839/TGFont#24]
如图所示，字体出问题的地方主要在用户名称和标题栏

![image](https://user-images.githubusercontent.com/5327960/49593610-ed8f0900-f9ae-11e8-9710-f72302586d6e.png)

![image](https://user-images.githubusercontent.com/5327960/49593483-9e48d880-f9ae-11e8-9381-7bbee779baac.png)

**Comment by ysc3839** [comment]
图片看不出问题。请把 TGFont.json 文件的内容发上来。

**Comment by CeresCa** [comment]
```json
{
	"fonts": {
		"SimSun": {
			"replace": "Microsoft YaHei UI",
			"#size": 0,
			"#width": 0,
			"#weight": 0,
			"#italic": false,
			"#underLine": false,
			"#strikeOut": false
		}
	},
	"debug": false
}
```
我用的是默认配置，不过系统的雅黑替换成了Noble Scarlet字体，  
升级后标题等地方的中文看起来像是衬线字体的样子，不知道是hint还是tg字体fallback的问题

**Comment by ysc3839** [comment]
你可能搞错了，衬线字体是宋体这样的。
https://zh.wikipedia.org/wiki/衬线体#/media/File:Chinese_typefaces_(_In_accordance_with_MOE,_ROC).svg

**Comment by CeresCa** [comment]
好的，多谢
