### ISSUE TITLE
其他软件需要什么条件才能使用这个字体调整工具？

### ISSUE THREAD

**Issue by airium** [ysc3839/TGFont#26]
> 修改 Telegram desktop Windows 版字体的简单的 hook 工具. (***理论上也支持别的软件***)

请问其他软件需要什么条件才能使用这个字体调整工具？
试了一圈，好像成功的不多。

**Comment by ysc3839** [comment]
@airium 1. 是32位程序
2. 导入表中包含 winmm.dll
3. 使用 GDI 字体

**Comment by airium** [comment]
感谢解释！
