### ISSUE TITLE
启动失败，提示找不到字体

### ISSUE THREAD

**Issue by XGZepto** [ysc3839/TGFont#27]
RT。默认的 Microsoft YaHei UI 也加载失败，提示  `[LoadUserFonts] FindFirstFile failed! (3)`。
出来的显示效果是这样的

![](https://drive.xgzepto.cn/images/2019/01/19/Issue.png)

**Comment by ysc3839** [comment]
LoadUserFonts 是加载用户字体，在没有 fonts 文件夹的情况下出现这个提示是正常的。
请发配置文件看看。

**Comment by XGZepto** [comment]
> LoadUserFonts 是加载用户字体，在没有 fonts 文件夹的情况下出现这个提示是正常的。
> 请发配置文件看看。

就是默认的配置

```
{
	"fonts": {
		"SimSun": {
			"replace": "Microsoft YaHei UI",
			"#size": 0,
			"#width": 0,
			"#weight": 0,
			"#italic": false,
			"#underLine": false,
			"#strikeOut": false,
			"#charSet": 0,
			"#outPrecision": 0,
			"#clipPrecision": 0,
			"#quality": 0,
			"#pitchAndFamily": 0
		}
	},
	"debug": false
}

```

**Comment by ysc3839** [comment]
你手动替换过系统字体？微软雅黑不是这样的。

**Comment by ysc3839** [comment]
我没试过直接替换系统字体，建议你直接在配置文件中使用这个字体。

**Comment by XGZepto** [comment]
> 我没试过直接替换系统字体，建议你直接在配置文件中使用这个字体。

这个字体的名字在 Windows 设置里就是 Microsoft YaHei UI。

我尝试在配置文件中使用 Source Han Sans CN，重启之后的显示效果还是那样，Log 也是 `[LoadUserFonts] FindFirstFile failed! (3)`。

**Comment by ysc3839** [comment]
@XGZepto 有可能 Telegram 就没使用 SimSun 吧？看看 log 文件中使用了哪些字体，替换别的试试。

**Comment by XGZepto** [comment]
> @XGZepto 有可能 Telegram 就没使用 SimSun 吧？看看 log 文件中使用了哪些字体，替换别的试试。

Log 文件里没提到有哪些字体。

我在配置里加上了 MS UI Gothic 和 OpenSans，依然不管用。

**Comment by ysc3839** [comment]
@XGZepto 你确定没有？发 log 看看？

**Comment by XGZepto** [comment]
> @XGZepto 你确定没有？发 log 看看？

```
[LoadUserFonts] FindFirstFile failed! (3)
[LoadUserFonts] FindFirstFile failed! (3)
[LoadUserFonts] FindFirstFile failed! (3)
```

没了。

**Comment by ysc3839** [comment]
@XGZepto 可能是 hook 失败了，完全替换不了字体了。这种情况我也不知道怎么办。

**Comment by XGZepto** [comment]
> @XGZepto 可能是 hook 失败了，完全替换不了字体了。这种情况我也不知道怎么办。

有没有可能和 MacType 冲突？

**Comment by ysc3839** [comment]
@XGZepto 应该是的。
