### ISSUE TITLE
Failed to start Telegram 1.0 in Windows XP SP3

### ISSUE THREAD

**Issue by roytam1** [ysc3839/TGFont#4]
It shows a message box and exits:
Exception Processing Message c0000145 Parameters c0000142 764ebf7c 764ebf7c 764ebf7c

I tried to compile it and I found that LoadLibrary failed and GetLastError() returns 998.

**Comment by ysc3839** [comment]
I have deleted my XP virtual machine some weeks ago. So I can't test it now. In fact I don't like to support XP.
PS: You can hit <kbd>Ctrl+C</kbd> to copy that message.

**Comment by ysc3839** [comment]
Tested. No problem.

**Comment by macelii** [comment]
一台老机器，碰上同样的问题，下载的最新的1.3，错误报告一样。
如果不想花太多时间支持老机器，可否告知一下哪个版本上次测试没问题的是哪个版本？感谢！
![1](https://user-images.githubusercontent.com/15188710/28812384-11e35656-76c7-11e7-9d35-3e2a418fe924.png)

**Comment by macelii** [comment]
目测所有releases都会报上面这个问题，已测试

**Comment by ysc3839** [comment]
我在虚拟机中的XP测试是没问题的……这种情况我也不知道该怎么办。

**Comment by macelii** [comment]
:-(
好的，暂时就这样吧
