### ISSUE TITLE
将 winmm.dll 放入 Telegram 根目录后,字体没有任何变化

### ISSUE THREAD

**Issue by notastudio** [ysc3839/TGFont#5]
Windows 7, Telegram Desktop 1.1.23
我将 `TGFont.dll` 更名为 `winmm.dll` 后放入 `C:\Users\XXX\AppData\Roaming\Telegram Desktop`, 重启 Telegram 后字体仍然是默认的宋体,也没有自动建立 `TGFont.json`. 我手动建立这个文件并输入内容后再次重启,字体仍然没有任何变化.
这是什么原因导致的?

**Comment by ysc3839** [comment]
@notastudio 可能是某些安全软件阻止？

**Comment by notastudio** [comment]
系统裸奔,什么安全软件都没开.

**Comment by ysc3839** [comment]
@notastudio 那我也不清楚了

**Comment by yhchen0906** [comment]
之前測試了一下，如果系統已經安裝了很多字型的話，好像會導致該 dll 崩潰
(我是用 logging 的功能做測試的，如果安裝的字型太多的話，會完全看不到 log)

**Comment by ysc3839** [comment]
@yhchen0906 完全看不到 log 应该不是崩溃，而是没有生效。请问首次运行时会自动创建 TGFont.json 吗？

**Comment by yhchen0906** [comment]
會 我有交叉比對過了

**Comment by ysc3839** [comment]
@yhchen0906 那我也不清楚什么情况了

**Comment by Crystal-RainSlide** [comment]
字体名称中是否含有 Unicode 字符？

**Comment by yuebing233** [comment]
https://blog.toby.moe/telegram-font/
