### ISSUE TITLE
有人知道ubuntu怎么搞吗。。

### ISSUE THREAD

**Issue by livc** [ysc3839/TGFont#6]

**Comment by ysc3839** [comment]
Related discussion: https://www.v2ex.com/t/405515

**Comment by livc** [comment]
@ysc3839 哇，这个是你啊，太巧了。

**Comment by ysc3839** [comment]
```c
#include <stdio.h>
#include <unistd.h>
#include <dlfcn.h>
int FT_New_Face(void *library, const char* filepathname, signed long face_index, void *aface)
{
	static int (*orig_FT_New_Face)(void *, const char*, signed long, void *) = NULL;
	if (!orig_FT_New_Face)
		orig_FT_New_Face = dlsym(RTLD_NEXT, "FT_New_Face");

	//puts("FT_New_Face Test!");
	return orig_FT_New_Face(library, "/path/to/test/font.ttc", face_index, aface);
}
```
```shell
gcc hooktest.c -o hooktest.so -fPIC -shared -ldl -D_GNU_SOURCE
export LD_PRELOAD=`pwd`/hooktest.so
telegram-desktop
```
在 Lubuntu 17.10 x64 下测试成功。

**Comment by daya-prac** [comment]
@ysc3839 我在Linuxmint18.3（基于ubuntu的操作系统）上试了一下没有成功，请问我还可以做哪些尝试？

**Comment by ysc3839** [comment]
@daya-prac 说说的你步骤？你不会没改代码吧？代码里要写字体文件路径的。

**Comment by daya-prac** [comment]
@ysc3839 配置了字体路径的

**Comment by ysc3839** [comment]
@daya-prac 把 puts 那一行取消注释，然后看看有没有输出信息。

**Comment by daya-prac** [comment]
@ysc3839 取消注释重新编译了一下，没有任何输出

**Comment by ysc3839** [comment]
@daya-prac 那说明没有调用这个函数，具体什么情况我就说不清了……

**Comment by daya-prac** [comment]
@ysc3839 好的，谢谢了

**Comment by daya-prac** [comment]
@ysc3839 对了“filepathname”这里是要替换成Telegram的文件路径吗

**Comment by ysc3839** [comment]
@daya-prac 不需要

**Comment by daya-prac** [comment]
@ysc3839 hooktest.c的源文件需要跟Telegram的二进制文件放在同一文件夹下面之后再编译吗

**Comment by ysc3839** [comment]
@daya-prac 不需要，随便放哪都行

**Comment by ssfdust** [comment]
感谢 成功。

**Comment by BackTrackCRoot** [comment]
xUbuntu 18.04 LTS HOOK失败 我尝试GDB调试 会触发FT_New_Face函数断点 ，但是没有任何输出 字体也修改失败

**Comment by ysc3839** [comment]
@BackTrackCRoot 有可能程序并没有使用 FreeType?

**Comment by BackTrackCRoot** [comment]
@ysc3839 我感觉应该是了 Linux的字体方面API我不是太熟 不知道还有其他函数么 还望指点一下 谢谢！

**Comment by ysc3839** [comment]
@BackTrackCRoot 我也不太熟

**Comment by BackTrackCRoot** [comment]
@ysc3839 哦哦 谢谢  那我再研究研究

**Comment by chewnglow** [comment]
@ysc3839 您好，我在18.04LTS不慎没有更改字体路径，导致现在QT显示异常，请问如何恢复正常呢？感谢！

**Comment by ysc3839** [comment]
@chewnglow 重启系统无效吗？

**Comment by chewnglow** [comment]
@ysc3839 重启之后QT就变得比较模糊了，后来直接删除了hooktest.c和hooktest.so，现在的情况是因为错误hook变得奇怪的字体渲染正常了，但是重启之后的字体模糊仍存在，另外还存在显示不正确的情况，如shell和部分窗口有异常白线、系统监视器刷新时会有白线等。
![Screenshot_20190408_183009](https://user-images.githubusercontent.com/22649869/55718736-07a92880-5a2f-11e9-848e-a4926272fefe.png)
![Screenshot_20190408_183749](https://user-images.githubusercontent.com/22649869/55718737-07a92880-5a2f-11e9-8219-da180b6bb398.png)

**Comment by ysc3839** [comment]
@chewnglow 如果你使用的是 `export LD_PRELOAD` 那重启后应该会完全恢复。

**Comment by subB1ss** [comment]
ubuntu 22.04.1 LTS
Telegram Desktop 4.2
HOOK成功，感谢
