### ISSUE TITLE
请问uwp 版本的telegram 怎么用? 

### ISSUE THREAD

**Issue by Bright-W** [ysc3839/TGFont#7]
系统win10 英文, telegram uwp中文显示用的日文字体.

**Comment by ysc3839** [comment]
应该没有办法使用。

**Comment by ArianeLu** [comment]
![image](https://user-images.githubusercontent.com/4962408/36641551-31ebdb82-1a6c-11e8-8647-203c4c92e803.png)

在1709(16299.248)上通过安全选项卡赋予所有权限也没办法复制文件进去，但是可以用Windows以外的系统复制文件进来，升级之后需要重新操作
